---
title: "ChangeBlindness"
format: html
editor: visual
---

## Packages

```{r}
library(tidyverse)
library(easystats)
library(ggplot2)
library(lme4)
library(lmerTest)
library(quickpsy)
library(buildmer)
library(geepack)
library(performance)
library(see)
library(cvms)
library(caret)
library(pROC)
library(ggeffects)
library(patchwork)
library(cowplot)
library(RColorBrewer)
library(lsmeans)
library(rio)
library(afex)
library(knitr)
```

## Raw Data

```{r}
raw.responses = read.csv("responses.csv")
```

## Clean up Data

```{r}
trial.data = raw.responses %>%
  # Remove unnecessary columns and rows 
  select(-1:-17) %>%
  filter(!row_number() %in% c(1,2)) %>%
  # Rename headers to something usable
  rename(c("PID" = "Q1",
           "Age" = "Q2",
           "Gender" = "Q3",
           "CorrectiveLenses" = "Q4",
           "EyeConditionBool" = "Q5",
           "EyeConditionText" = "Q5_1_TEXT",
           "AverageDrivingHours" = "Q6")) %>%
  # Filter out PID 0 (test IDs)
  filter(PID != 0) %>%
  mutate(
    # Normalize responses from the pairwise comparisons
    across(TLX_W_1:TLX_W_15, ~ as.integer(as.integer(.x)/2)),
    across(TLX_Mental_1:TLX_Frustration_1, ~ as.integer(.x)),
    across(TLX_Mental_1:TLX_Frustration_1, ~ ifelse(is.na(.x), 0, .x)),
  ) %>%
  mutate(
    # Calculate weights
    effortWeight = (1-TLX_W_1)+(TLX_W_3)+(TLX_W_9)+(TLX_W_12)+(1-TLX_W_14),
    frustrationWeight = (TLX_W_2)+(TLX_W_4)+(TLX_W_5)+(1-TLX_W_9)+(1-TLX_W_15),
    mentalWeight = (TLX_W_8)+(TLX_W_10)+(1-TLX_W_12)+(1-TLX_W_13)+(TLX_W_15),
    performanceWeight = (TLX_W_1)+(1-TLX_W_5)+(TLX_W_7)+(1-TLX_W_10)+(1-TLX_W_11),
    physicalWeight = (1-TLX_W_4)+(1-TLX_W_6)+(1-TLX_W_7)+(TLX_W_13)+TLX_W_14,
    temporalWeight = (1-TLX_W_2)+(1-TLX_W_3)+(TLX_W_6)+(1-TLX_W_8)+(TLX_W_11)
  ) %>%
  mutate(
    # Calculate final scores
    finalUnweightedScore = (TLX_Effort_1 + TLX_Frustration_1 + 
                              TLX_Mental_1 + TLX_Performance_1 + 
                              TLX_Physical_1 + TLX_Temporal_1) / 6,
    finalWeightedScore = ((TLX_Mental_1 * mentalWeight) + 
                            (TLX_Frustration_1 * frustrationWeight) + 
                            (TLX_Effort_1 * effortWeight) + 
                            (TLX_Performance_1 * performanceWeight) + 
                            (TLX_Physical_1 * physicalWeight) + 
                            (TLX_Temporal_1 * temporalWeight)) / 15
  )
```

## Descriptive Statistics

```{r}
summary = trial.data %>%
  group_by(Task) %>%
  summarize(count = n(),
            across(TLX_Mental_1:TLX_Frustration_1, ~ mean(.x)),
            across(finalUnweightedScore:finalWeightedScore, ~ mean(.x)))
```

## Plots

### finalWeighted

```{r}
(fit <- aov_ez(data = trial.data,
               id = "PID",
               dv = "finalWeightedScore",
               between = c('Task'),
               type = 3,
               factorize = FALSE))
summary(fit)

# nicer table
kable(nice(fit,es="ges"))

#describe(df$duration)

(t <- lsmeans(fit, c('Task'), contr = 'pairwise'))
tab <- summary(t$lsmeans)

fdur.plot <- ggplot(tab,
                    aes(x = Task, y = lsmean)) +
                    geom_bar(position=position_dodge(), stat="identity",
                          colour="#303030",fill="#d94801",alpha=.7) +
#                         colour="#303030",fill="#045a8d",alpha=.7) +
#                   scale_fill_brewer(palette="Blues") +
                    scale_fill_brewer(palette="Oranges") +
                    geom_errorbar(aes(ymin=lsmean-SE, ymax=lsmean+SE),
                                  width=.2, size=.3,
                                  position=position_dodge(.9)) +
		    theme_bw(base_size=18) + 
                    ylab("Weighted TLX Score") +
                    xlab('Task') +
                    theme(legend.position = "none")

plotName = "tlx_weighted.pdf"
pdf(plotName, encoding="ISOLatin2")
print(fdur.plot)
dev.off()
```

### finalUnweighted

```{r}
(fit <- aov_ez(data = trial.data,
               id = "PID",
               dv = "finalUnweightedScore",
               between = c('Task'),
               type = 3,
               factorize = FALSE))
summary(fit)

# nicer table
kable(nice(fit,es="ges"))

#describe(df$duration)

(t <- lsmeans(fit, c('Task'), contr = 'pairwise'))
tab <- summary(t$lsmeans)

fdur.plot <- ggplot(tab,
                    aes(x = Task, y = lsmean)) +
                    geom_bar(position=position_dodge(), stat="identity",
                          colour="#303030",fill="#d94801",alpha=.7) +
#                         colour="#303030",fill="#045a8d",alpha=.7) +
#                   scale_fill_brewer(palette="Blues") +
                    scale_fill_brewer(palette="Oranges") +
                    geom_errorbar(aes(ymin=lsmean-SE, ymax=lsmean+SE),
                                  width=.2, size=.3,
                                  position=position_dodge(.9)) +
		    theme_bw(base_size=18) + 
                    ylab("Unweighted TLX Score") +
                    xlab('Task') +
                    theme(legend.position = "none")

plotName = "tlx_unweighted.pdf"
pdf(plotName, encoding="ISOLatin2")
print(fdur.plot)
dev.off()
```

## AOI Stuff

```{r}
raw.aoi = read.csv("fxtn-aois.csv")
```

### Detection Status and percentFixated (only stimuli that had a change)

```{r}
aoi.data = raw.aoi

summary.aoi = aoi.data %>% 
  group_by(subj, detectionstatus) %>%
  filter(stim != "set_4") %>%
  summarise(changeFixated = length(which(aoi_order == 1)),
            changeNotFixated = length(which(aoi_order != 1))) %>%
  mutate(percentFixated = changeFixated / (changeFixated + changeNotFixated))


(fit <- aov_ez(data = summary.aoi,
               id = "subj",
               dv = "percentFixated",
               between = c('detectionstatus'),
               type = 3,
               factorize = FALSE))
summary(fit)

# nicer table
kable(nice(fit,es="ges"))

#describe(df$duration)

(t <- lsmeans(fit, c('detectionstatus'), contr = 'pairwise'))
tab <- summary(t$lsmeans)

fdur.plot <- ggplot(tab,
                    aes(x = detectionstatus, y = lsmean)) +
                    geom_bar(position=position_dodge(), stat="identity",
                          colour="#303030",fill="#d94801",alpha=.7) +
#                         colour="#303030",fill="#045a8d",alpha=.7) +
#                   scale_fill_brewer(palette="Blues") +
                    scale_fill_brewer(palette="Oranges") +
                    geom_errorbar(aes(ymin=lsmean-SE, ymax=lsmean+SE),
                                  width=.2, size=.3,
                                  position=position_dodge(.9)) +
		    theme_bw(base_size=18) + 
                    ylab("Change AOI Fixation Percentage") +
                    xlab('Change Detected') +
                    theme(legend.position = "none")

plotName = "fixations-detection.pdf"
pdf(plotName, encoding="ISOLatin2")
print(fdur.plot)
dev.off()
```

### Last X Fixations

```{r}
aoi.data.lastX = aoi.data %>%
  filter(stim != "set_4") %>%
  group_by(subj, stim) %>%
  slice(tail(row_number(), 10)) %>%
  ungroup() %>%
  group_by(subj, detectionstatus) %>%
  summarise(changeFixated = length(which(aoi_order == 1)),
            changeNotFixated = length(which(aoi_order != 1))) %>%
  mutate(percentFixated = changeFixated / (changeFixated + changeNotFixated))

(fit <- aov_ez(data = aoi.data.lastX,
               id = "subj",
               dv = "percentFixated",
               between = c('detectionstatus'),
               type = 3,
               factorize = FALSE))
summary(fit)

# nicer table
kable(nice(fit,es="ges"))

#describe(df$duration)

(t <- lsmeans(fit, c('detectionstatus'), contr = 'pairwise'))
tab <- summary(t$lsmeans)

fdur.plot <- ggplot(tab,
                    aes(x = detectionstatus, y = lsmean)) +
                    geom_bar(position=position_dodge(), stat="identity",
                          colour="#303030",fill="#d94801",alpha=.7) +
#                         colour="#303030",fill="#045a8d",alpha=.7) +
#                   scale_fill_brewer(palette="Blues") +
                    scale_fill_brewer(palette="Oranges") +
                    geom_errorbar(aes(ymin=lsmean-SE, ymax=lsmean+SE),
                                  width=.2, size=.3,
                                  position=position_dodge(.9)) +
		    theme_bw(base_size=18) + 
                    ylab("Change AOI Fixation Percentage") +
                    xlab('Change Detected') +
                    theme(legend.position = "none") + 
  scale_y_continuous(limits = c(0, NA), oob = scales::squish)

plotName = "lastX-fixations-detection.pdf"
pdf(plotName, encoding="ISOLatin2")
print(fdur.plot)
dev.off()
```

```{r}
df = raw.aoi %>%
  filter(aoi_order == 1)

(fit <- aov_ez(data = df,
               id = "subj",
               dv = "duration",
               between = c('stim'),
               type = 3,
               factorize = FALSE))
summary(fit)

# nicer table
kable(nice(fit,es="ges"))

#describe(df$duration)

(t <- lsmeans(fit, c('stim'), contr = 'pairwise'))
tab <- summary(t$lsmeans)

fdur.plot <- ggplot(tab,
                    aes(x = stim, y = lsmean)) +
                    geom_bar(position=position_dodge(), stat="identity",
                          colour="#303030",fill="#d94801",alpha=.7) +
#                         colour="#303030",fill="#045a8d",alpha=.7) +
#                   scale_fill_brewer(palette="Blues") +
                    scale_fill_brewer(palette="Oranges") +
                    geom_errorbar(aes(ymin=lsmean-SE, ymax=lsmean+SE),
                                  width=.2, size=.3,
                                  position=position_dodge(.9)) +
		    theme_bw(base_size=18) + 
                    ylab("Changed AOI Fixation Percentage") +
                    xlab('Change Detected') +
                    theme(legend.position = "none")

plotName = "temp.pdf"
pdf(plotName, encoding="ISOLatin2")
print(fdur.plot)
dev.off()
embedFonts(plotName, "pdfwrite", outfile = plotName,
        fontpaths =
          c("/sw/share/texmf-dist/fonts/type1/urw/",
            "/usr/share/texmf/fonts/type1/urw/",
            "/usr/local/teTeX/share/texmf-dist/fonts/type1/urw/",
            "/opt/local/share/texmf-texlive/fonts/type1/",
            "/usr/share/texmf-texlive/fonts/type1/urw/",
            "/usr/local/texlive/texmf-local/fonts/type1/urw/"))
```

### Mean Fixation Duration

```{r}
aoi.data.means = raw.aoi

(fit <- aov_ez(data = aoi.data.means,
               id = "subj",
               dv = "duration",
               within = c('aoi_order'),
               type = 3,
               factorize = FALSE, na.rm = FALSE))
summary(fit)

# nicer table
kable(nice(fit,es="ges"))

(t <- lsmeans(fit, c('aoi_order'), contr = 'pairwise'))
tab <- summary(t$lsmeans)

samp.plot <- ggplot(tab,
                    aes(x = aoi_order, y = lsmean)) +
                    geom_bar(position=position_dodge(), stat="identity",
                          colour="#303030",fill="#d94801",alpha=.7) +
#                         colour="#303030",fill="#045a8d",alpha=.7) +
#                   scale_fill_brewer(palette="Blues") +
                    scale_fill_brewer(palette="Oranges") +
                    geom_errorbar(aes(ymin=lsmean-SE, ymax=lsmean+SE),
                                  width=.2, size=.3,
                                  position=position_dodge(.9)) +
		    theme_bw(base_size=18) + 
                    ylab("Mean fixation duration (ms.)") +
                    xlab('AOI') +
                    theme(legend.position = "none")

plotName = "detection-means.pdf"
pdf(plotName, encoding="ISOLatin2")
print(samp.plot)
dev.off()
```
